#!/bin/bash
# dependencies to run this script: gum

CONFIG=".fgitconfig"
CONFIG_FILE="$HOME/$CONFIG"
ACCEPT="yes"
DECLINE="no"
COLOR_GREEN="#ffff8f"
COLOR_PINK="#ff69b4"
COLOR_WHITE="#ffffff"

touch "$CONFIG_FILE"

style_message() {
  gum style \
    --border="rounded" \
    --border-foreground=$COLOR_PINK \
    --bold \
    --foreground=$COLOR_WHITE \
    --margin="0 0" \
    "$1"
}

style_important() {
  gum style \
    --foreground=$COLOR_GREEN \
    "$1"
}

style_alert() {
  gum style \
    --foreground=$COLOR_PINK \
    "$1"
}

confirm () {
  gum choose \
    --header="$(style_message "$1")" \
    --cursor.foreground=$COLOR_GREEN \
    $ACCEPT $DECLINE
}

create_branch() {
  prefix_message=$(style_message "branch prefix:")
  ticket_nr_message=$(style_message "ticket number: (leave empty if no ticket)")
  name_message=$(style_message "branch name:")

  prefix=$(gum choose \
    --header="$prefix_message" \
    --cursor="-> " \
    --cursor.foreground=$COLOR_GREEN \
    "feature" "fix" "hotfix" "none"
  )

  ticket_nr=$(gum input --header="$ticket_nr_message" --placeholder="ABCD-1234")
  name=$(gum input --header="$name_message" --placeholder="what-ever-you-want")

  if [[ -z $name ]]; then
    style_message "$(style_alert "branch creation aborted - no branch name provided")"
    exit 1
  fi

  if [[ -n $ticket_nr ]]; then
    name="$ticket_nr-$name"
  fi

  if [[ $prefix != "none" ]]; then
    name="$prefix/$name"
  fi

  keep_name=$(confirm "Keep branch: $(style_important "$name")?")

  if [[ $keep_name == "$ACCEPT" ]]; then
    # write branch name and ticket number to config file
    echo "$name|$ticket_nr" >> "$CONFIG_FILE"
    git checkout -b "$name"
  else
    style_message "$(style_alert "branch creation aborted")"
  fi
}

commit_changes() {
  # get current branch name and get ticket number for branch
  current_branch_name=$(git rev-parse --abbrev-ref HEAD)
  file_content=$(grep -i "$current_branch_name" "$CONFIG_FILE")
  ticket_nr=$(echo "$file_content" | cut -d '|' -f 2)

  commit_message_message=$(style_message "commit message:")
  commit_message=$(gum input --header="$commit_message_message")

  if [[ -n $ticket_nr ]]; then
    commit_message="$ticket_nr: $commit_message"
  fi

  keep_message=$(confirm "Keep message: '$(style_important "$commit_message")'?")

  if [[ $keep_message == "$ACCEPT" ]]; then
    git commit -m "$commit_message"
  else
    style_message "$(style_alert "commit aborted")"
  fi
}

delete_branch() {
  current_branch_name=$(git rev-parse --abbrev-ref HEAD)

  if [[ $current_branch_name != "develop" ]]; then
    # try to checkout branch develop
    git checkout "develop" || {
      style_message "$(style_alert "something went wrong - failed to checkout branch develop")"
      exit 2
    }
  fi

  # get all branches except for develop and master, also remove * from current branch
  existing_branches=$(git branch | sed 's/^[* ]//' | sed "/develop/d" | sed "/master/d")

  if [[ -z $existing_branches ]]; then
    style_message "$(style_alert "no branches to delete")"
    exit 1
  fi

  linebreak=$'\n'
  hint="toggle selection using <SPACE> if multiple branches shown$linebreak<enter> to proceed"
  deletion_message=$(style_message "Choose branches for deletion$linebreak$hint")

  branches_to_delete=$(gum choose \
    --header="$deletion_message" \
    --cursor.foreground=$COLOR_GREEN \
    --cursor-prefix="[ ] " \
    --selected-prefix="[✓] " \
    --unselected-prefix="[ ] " \
    --no-limit \
    $existing_branches
  )

  if [[ -z $branches_to_delete ]]; then
    style_message "$(style_alert "no branches selected")"
    exit 1
  fi

  message=$'Delete following branches:\n'
  delete_branches=$(confirm "$message$(style_important "$branches_to_delete")")

  if [[ $delete_branches == "$ACCEPT" ]]; then
    git branch -d $branches_to_delete

    delimiter=$'\n'
    IFS="$delimiter" read -ra split_branches <<< $branches_to_delete

    for single_branch in $split_branches
    do
      grep_content=$(cat "$CONFIG_FILE" | grep "$single_branch")

      if [[ "$OSTYPE" == "linux-gnu" ]]; then
        # use GNU sed on linux
        sed -i "\|$single_branch|d" $CONFIG_FILE
      elif [[ "$OSTYPE" == "darwin"* ]]; then
        # use BSD sed on mac
        sed -i "" "\|$single_branch|d" $CONFIG_FILE
      fi
    done
  fi
}

if [[ $1 == "new" ]]; then
  create_branch
elif [[ $1 == "commit" ]]; then
  commit_changes
elif [[ $1 == "delete" ]]; then
  delete_branch
fi
